### ISSUE TITLE
Implement stochastic gradient descent

### ISSUE THREAD

**Issue by sgrimald89** [sgrimald89/instacart_kaggle#13]
It seems that the base logistic regression algorithm (gradient descent) might cause our computers to suffer due to the large data sets once we add enough features into our current models.  To address this, I will switch over our logistic regression algorithm to a stochastic gradient descent classifier that fits a logistic regression using stochastic gradient descent.

**Comment by neman018** [comment]
Sounds interesting. How are the OOS results?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by sgrimald89** [comment]
I'm finishing up some tests. It seems my computer won't be able to handle running this with the dummy variables, so I've scrapped that idea for now. If someone has a computer with > 16GB RAM though, it might be good to test it out.

The performance though looks comparable to the model with the usual gradient descent implementation.

I'll report further when all's done running

**Comment by sgrimald89** [comment]
A slight loss in f1 score, but it works much faster, so I think it's worth the sacrifice. Not like we have much of a chance of winning the competition (especially now that it's over :P)

**Comment by sgrimald89** [comment]
See #14
